# Generated by Django 3.1.1 on 2020-11-28 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(default='profile_picture/default.png', upload_to='profile_picture/')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=32)),
                ('date_registred', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('book_file', models.FileField(upload_to='books/')),
                ('book_cover', models.ImageField(default='book_cover/default.png', upload_to='book_cover/')),
                ('description', models.CharField(default='', max_length=500)),
                ('writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mainapp.writer')),
            ],
        ),
    ]
