# Generated by Django 3.1.1 on 2020-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='profile_picture_height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='writer',
            name='profile_picture_offset_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writer',
            name='profile_picture_offset_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='writer',
            name='profile_picture_width',
            field=models.IntegerField(default=100),
        ),
    ]
