# Generated by Django 3.1.1 on 2020-12-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201204_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='profile_picture_width',
        ),
    ]
