# Generated by Django 3.1.1 on 2021-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201204_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writer',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='writer',
            name='first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='writer',
            name='last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='writer',
            name='middle_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
