# Generated by Django 3.1.1 on 2021-04-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210308_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='writer',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
